/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "tertiary-container": "#8990a8",
        "surface-container-lowest": "#010f1f",
        "on-primary": "#1000a9",
        "primary": "#c0c1ff",
        "on-primary-fixed": "#07006c",
        "surface": "#051424",
        "on-primary-container": "#0d0096",
        "surface-dim": "#051424",
        "surface-container-low": "#0d1c2d",
        "on-secondary-fixed-variant": "#5516be",
        "secondary-fixed": "#e9ddff",
        "on-tertiary": "#283044",
        "on-error-container": "#ffdad6",
        "secondary-container": "#571bc1",
        "tertiary-fixed": "#dae2fd",
        "tertiary-fixed-dim": "#bec6e0",
        "on-error": "#690005",
        "inverse-surface": "#d4e4fa",
        "outline-variant": "#464554",
        "error": "#ffb4ab",
        "primary-container": "#8083ff",
        "on-secondary-fixed": "#23005c",
        "secondary-fixed-dim": "#d0bcff",
        "secondary": "#d0bcff",
        "tertiary": "#bec6e0",
        "primary-fixed-dim": "#c0c1ff",
        "on-background": "#d4e4fa",
        "on-tertiary-container": "#22293d",
        "outline": "#908fa0",
        "surface-container-high": "#1c2b3c",
        "surface-tint": "#c0c1ff",
        "primary-fixed": "#e1e0ff",
        "on-tertiary-fixed": "#131b2e",
        "on-secondary-container": "#c4abff",
        "on-surface": "#d4e4fa",
        "inverse-primary": "#494bd6",
        "on-surface-variant": "#c7c4d7",
        "on-primary-fixed-variant": "#2f2ebe",
        "on-secondary": "#3c0091",
        "inverse-on-surface": "#233143",
        "surface-container": "#122131",
        "background": "#051424",
        "surface-container-highest": "#273647",
        "on-tertiary-fixed-variant": "#3f465c",
        "surface-variant": "#273647",
        "surface-bright": "#2c3a4c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "2rem",
        "section-margin": "3rem",
        "inner-padding": "1.25rem",
        "grid-gutter": "1.5rem",
        "stack-gap": "1.5rem"
      },
      fontFamily: {
        "body-md": ["Inter"],
        "label-caps": ["Geist"],
        "body-sm": ["Inter"],
        "headline-lg": ["Geist"],
        "body-lg": ["Inter"],
        "headline-xl": ["Geist"],
        "mono-data": ["Geist"],
        "headline-md": ["Geist"],
        "headline-lg-mobile": ["Geist"]
      },
      fontSize: {
        "body-md": ["16px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg": ["30px", { "lineHeight": "38px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "mono-data": ["14px", { "lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-md": ["20px", { "lineHeight": "28px", "letterSpacing": "0em", "fontWeight": "600" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [],
}
